<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<!-- Standalone Single-File EXE Settings -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishReadyToRun>true</PublishReadyToRun>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" Version="8.0.0" />
		<PackageReference Include="DiscUtils.Core" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Iso9660" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Udf" Version="0.16.13" />
		<PackageReference Include="DiscUtils.Streams" Version="0.16.13" />
	</ItemGroup>

</Project>