// SPDX-License-Identifier: GPL-3.0-or-later
using System.Buffers.Binary;
using System.Text;
using Bootrix.Core.Boot.Dos;
using Bootrix.Core.FileSystems.Fat;
using Bootrix.Core.Tests.Boot;
using Bootrix.Core.Writing.Dos;

namespace Bootrix.Core.Tests.Writing.Dos;

/// <summary>
/// A stand-in for diskcopy.dll and the startup diskette inside it, made of generated bytes: the files have the sizes and
/// the byte sequences that <see cref="MsDosFloppy"/> looks for, nothing else is Microsoft's. The real files never enter the repository.
/// </summary>
internal static class MsDosFixtures
{
    public const int IoSysLength = 116_736;
    public const int CommandComLength = 93_040;
    public const int IoSysPatchAt = 0x3AA;
    public const int CommandPatchAt = 0x6510;

    private static readonly byte[] IoSysContext = [0xFA, 0x80, 0x75, 0x09, 0x8D, 0xB6, 0x99, 0x00];
    private static readonly byte[] CommandContext = [0x15, 0x80, 0xFA, 0x03, 0x75, 0x10, 0xB8, 0x0E];

    public static readonly string[] LocaleNames =
    [
        "MODE.COM", "KEYB.COM", "KEYBOARD.SYS", "KEYBRD2.SYS", "KEYBRD3.SYS", "KEYBRD4.SYS", "DISPLAY.SYS",
        "EGA.CPI", "EGA2.CPI", "EGA3.CPI",
    ];

    public static byte[] IoSys() => WithContext(PeBuilder.Pattern(IoSysLength, 11), 0x3A8, IoSysContext);

    public static byte[] CommandCom() => WithContext(PeBuilder.Pattern(CommandComLength, 12), 0x650C, CommandContext);

    /// <summary>The boot sector of the stand-in diskette: a jump, recognizable code and the signature. Its BPB is that of a 1.44 MB disk.</summary>
    public static byte[] BootSector()
    {
        var sector = PeBuilder.Pattern(512, 13);
        sector[0] = 0xEB;
        sector[1] = 0x3C;
        sector[2] = 0x90;
        sector[510] = 0x55;
        sector[511] = 0xAA;
        return sector;
    }

    public static byte[] Floppy(byte[]? ioSys = null, byte[]? commandCom = null, bool withLocaleFiles = true)
    {
        var preset = FloppyPreset.All.Single(p => p.Name == "1.44M");
        var image = new byte[preset.TotalBytes];
        using var volume = new MemoryStream(image);
        FatFormatter.Format(volume, preset.ToOptions() with { BootCode = BootSector() });

        var files = new List<DosFile>
        {
            new("\\COMMAND.COM", commandCom ?? CommandCom()),
            new("\\IO.SYS", ioSys ?? IoSys(), DosFile.SystemFile),
            new("\\MSDOS.SYS", "BootGUI=0"u8.ToArray(), DosFile.SystemFile),
        };
        if (withLocaleFiles)
        {
            files.AddRange(LocaleNames.Select((name, i) => new DosFile("\\" + name, PeBuilder.Pattern(1500 + i * 700, 20 + i))));
        }

        DosVolumeWriter.Write(volume, files);
        return image;
    }

    /// <summary>A PE file with a custom resource of type <paramref name="typeName"/> that holds <paramref name="payload"/>.</summary>
    public static byte[] Dll(byte[] payload, string typeName = "BINFILE", uint? declaredSize = null)
    {
        const int sectionRva = 0x3000;
        var name = Encoding.Unicode.GetBytes(typeName);
        const int dataEntry = 72;
        const int nameString = 88;
        var data = (nameString + 2 + name.Length + 7) / 8 * 8;
        var section = new byte[data + payload.Length];

        void Entry(int at, uint nameOrId, uint target)
        {
            BinaryPrimitives.WriteUInt32LittleEndian(section.AsSpan(at), nameOrId);
            BinaryPrimitives.WriteUInt32LittleEndian(section.AsSpan(at + 4), target);
        }

        BinaryPrimitives.WriteUInt16LittleEndian(section.AsSpan(12), 1); // root: one named entry, the type
        Entry(16, 0x80000000u | nameString, 0x80000000u | 24);
        BinaryPrimitives.WriteUInt16LittleEndian(section.AsSpan(24 + 14), 1); // type: one ID entry
        Entry(40, 1, 0x80000000u | 48);
        BinaryPrimitives.WriteUInt16LittleEndian(section.AsSpan(48 + 14), 1); // item: one language
        Entry(64, 1033, dataEntry);
        BinaryPrimitives.WriteUInt32LittleEndian(section.AsSpan(dataEntry), sectionRva + (uint)data);
        BinaryPrimitives.WriteUInt32LittleEndian(section.AsSpan(dataEntry + 4), declaredSize ?? (uint)payload.Length);
        BinaryPrimitives.WriteUInt16LittleEndian(section.AsSpan(nameString), (ushort)typeName.Length);
        name.CopyTo(section, nameString + 2);
        payload.CopyTo(section, data);

        var pe = PeBuilder.Typical();
        pe.RawResourceSection = section;
        return pe.Build();
    }

    private static byte[] WithContext(byte[] content, int at, byte[] context)
    {
        context.CopyTo(content, at);
        return content;
    }
}
