<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bootrix.Core</RootNamespace>
    <AssemblyName>Bootrix.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LTRData.DiscUtils.Core" />
    <PackageReference Include="LTRData.DiscUtils.Fat" />
    <PackageReference Include="LTRData.DiscUtils.Iso9660" />
    <PackageReference Include="LTRData.DiscUtils.Udf" />
    <PackageReference Include="LTRData.DiscUtils.Streams" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Boot\revocations.json" LogicalName="Bootrix.Core.Boot.revocations.json" />
  </ItemGroup>

</Project>
