<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bootrix.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Bootrix.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="LTRData.DiscUtils.Core" />
    <PackageReference Include="LTRData.DiscUtils.Fat" />
    <PackageReference Include="LTRData.DiscUtils.Iso9660" />
    <PackageReference Include="LTRData.DiscUtils.Udf" />
    <PackageReference Include="LTRData.DiscUtils.Streams" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="LzfseSharp" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Boot\revocations.json" LogicalName="Bootrix.Core.Boot.revocations.json" />
    <EmbeddedResource Include="Tiny\Profiles\*.json" />
    <EmbeddedResource Include="Images\Families\*.json" />
    <EmbeddedResource Include="Images\Policy\*.json" />
    <EmbeddedResource Include="Catalog\Rescue\rescue-catalog.json" LogicalName="Bootrix.Core.Catalog.Rescue.rescue-catalog.json" />
    <EmbeddedResource Include="Catalog\Distros\Keys\*.asc" LogicalName="Bootrix.Core.Catalog.Distros.Keys.%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\assets\third-party\syslinux\6.03\*" LogicalName="Bootrix.Core.Boot.Syslinux.6.03/%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\assets\third-party\syslinux\6.04-pre1\*" LogicalName="Bootrix.Core.Boot.Syslinux.6.04-pre1/%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\assets\third-party\syslinux-mbr\mbr.bin;..\..\assets\third-party\syslinux-mbr\mbr_f.bin;..\..\assets\third-party\syslinux-mbr\gptmbr.bin" LogicalName="Bootrix.Core.Boot.Syslinux.mbr/%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\assets\third-party\grub\2.12\*" LogicalName="Bootrix.Core.Boot.Grub.2.12/%(Filename)%(Extension)" />
    <EmbeddedResource Include="..\..\assets\third-party\uefi-ntfs\uefi-ntfs.img" LogicalName="Bootrix.Core.Writing.Linux.uefi-ntfs.img" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bootrix.Core.Tests" />
  </ItemGroup>

</Project>
